### ISSUE TITLE
Error with Popups font

### ISSUE THREAD

**Issue by qeqbwd** [toxicity188/BetterHud#10]
When I input /hud reload /iazip everything is normal.
<img width="1278" alt="mmexport1714667425955" src="https://github.com/toxicity188/BetterHud/assets/163020282/0afa17ef-e39c-4179-88be-642979b985a0">
But after restarting the server, there's an error with the Popups font, while the rest of the HUD is normal.
<img width="1280" alt="mmexport1714667248809" src="https://github.com/toxicity188/BetterHud/assets/163020282/500d449d-ad94-416b-a28b-c99f0611b9e3">

**Comment by toxicity188** [comment]
I can't support you only this image. go to my discord channel and send me your resource pack please.

**Comment by qeqbwd** [comment]
Sure, I have privately sent the compressed file to your Discord. Please take a look, and thank you very much for your help.

**Comment by qeqbwd** [comment]
Hello, I have identified the cause of the popups error. It's because BetterHUD doesn't support the skill release mode of Using key combos in MMOCore. When I switch to the mode of Using the [1] to [9] keys, everything returns to normal. I hope you can add support for the Using key combos mode. Thank you very much.

**Comment by Enclme** [comment]
> 我不能只支持你这张图片。转到我的 Discord 频道并将您的资源包发送给我。

Hello, may I ask if I clicked Connect but could not join discord I sent you a friend application on discord
