### ISSUE TITLE
GUI Scaling 

### ISSUE THREAD

**Issue by mitchngwen** [toxicity188/BetterHud#11]
This plugin is much much easier to use than crappyhud. Thank you for making this! I was wondering if or when you re going to add GUI scaling, because when I change the GUI scale huds change potion, they either move off screen or lower in the screen.

**Comment by rFalvan** [comment]
from server side, this is almost impossible to implement. As for off-screen offsets, I advise you to read this wiki page in more detail
https://github.com/toxicity188/BetterHud/wiki/huds
