### ISSUE TITLE
Hotbar Some items are displayed incorrectly

### ISSUE THREAD

**Issue by MoLiyi-WD** [toxicity188/BetterHud#12]
![image](https://github.com/toxicity188/BetterHud/assets/166040564/be564193-69ce-414a-91f1-d493b91587c7)
Normally it would look like this.
But beds, snorkels, flags, and heads have display problems.
![image](https://github.com/toxicity188/BetterHud/assets/166040564/0a99f717-a8af-4bb5-9899-cfc257d63260)
They will be displayed in their original location instead of the one I specified.

**Comment by toxicity188** [comment]
Head requires more core shader file. But this file have been used in many plugin like ModelEngine. So it is hard to supports directly.
