### ISSUE TITLE
number-format is not valid

### ISSUE THREAD

**Issue by Enclme** [toxicity188/BetterHud#13]
![1](https://github.com/toxicity188/BetterHud/assets/155731219/d5d1729c-0b99-4fa9-8533-7554652b6f04)
I formatted the number-format to expect only integer digits to be displayed, but it didn't work

**Comment by Sacred6959** [comment]
By default the number format is disabled so you need to enable it like: 
disable-number-format: false

Atte: Discord: Ariget

**Comment by toxicity188** [comment]
For now, it is rewritted
