### ISSUE TITLE
Betterhud is not  working 

### ISSUE THREAD

**Issue by antoilmalvagio** [toxicity188/BetterHud#14]
Hi I'm having this bug https://mclo.gs/xkUqhXh, BetterHud is not able to read font 1  and I have the font and the text in the folders. Could be caused by java 21? https://imgur.com/L541g6V  https://imgur.com/wdpyv7o I'm using purpur 1.20.4-2174

**Comment by antoilmalvagio** [comment]
Any news?

**Comment by toxicity188** [comment]
maybe your OS or JVM issue.
