### ISSUE TITLE
Shader ItemAdder error

### ISSUE THREAD

**Issue by Sorax5** [toxicity188/BetterHud#15]
Hello,
I use BetterHUD with ItemAdder.
I had a problem with the items turning black (see image below).

As indicated in the wiki, I have deactivated the text-effect and merge the betterHUD resource pack.

Could this be due to an incompatibility with Minecraft 1.21?

![Minecraft BetterHUD](https://github.com/toxicity188/BetterHud/assets/52173496/1270090c-81e2-4b72-81f3-a1d742abbdfd)

**Comment by toxicity188** [comment]
Disclaimer:
I do not response any problem with ItemsAdder or some kind of modified client
