### ISSUE TITLE
MIT License Violating GPLv3 Terms

### ISSUE THREAD

**Issue by kdhkr** [toxicity188/BetterHud#20]
Bukkit API, [distinctly being used in this project](https://github.com/toxicity188/BetterHud/blob/master/nms/v1_21_R1/src/main/kotlin/kr/toxicity/hud/nms/v1_21_R1/NMSImpl.kt#L34), is [licensed through GPLv3](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/LICENCE.txt).
GPLv3 does not allow linking to non-GPL compliant code and also prohibits licensing a derivative of a GPL licensed software (such as a Minecraft plugin) with an incompatible license.
Hence, the MIT License applied to this software is invalidated and thus overridden by the GPL Terms.
Consider re-licensing the software with GPLv3.

**Comment by toxicity188** [comment]
I think it's an unclear claim.
