### ISSUE TITLE
The backgrounds of the text are duplicated with an offset and so are the heads

### ISSUE THREAD

**Issue by NeyranDis** [toxicity188/BetterHud#33]
**Minecraft version - 1.21**
**Plugin version - 1.3 HOTFIX**

![image](https://github.com/user-attachments/assets/740100cf-3a41-4777-8203-7dfe18d64a04)

In the attached screenshot you can see how there is a shadow behind her head and you can also see in the background of the text that there are two of them and they intersect making the background less transparent

**Comment by toxicity188** [comment]
![화면 캡처 2024-08-26 134639](https://github.com/user-attachments/assets/81fbb809-0390-4c60-83fc-1ebddf05fc30)  
outline: false  
![화면 캡처 2024-08-26 134703](https://github.com/user-attachments/assets/cbc082bf-5a2d-469b-9d32-c6abe813c418)  
outline: true  

No problem.

**Comment by NeyranDis** [comment]
but I have them turned off, I have already tried this, on 1.20.6 there is no such error

**Comment by NeyranDis** [comment]
after switching to version 1.4 of the plugin the error disappeared
