### ISSUE TITLE
triggers not working

### ISSUE THREAD

**Issue by LegendaryElm327** [toxicity188/BetterHud#34]
Or so it seems, I use the entity_attack trigger and nothing happens, I tried to learn how to use it with the wiki example (I also tried the discord one) but I still couldn't get it to work, I'm almost sure it has to do with the trigger

![image](https://github.com/user-attachments/assets/fcf56313-3439-4d10-8f30-220742ca28e6)
![image](https://github.com/user-attachments/assets/c575dc18-813e-4f89-a9a1-52e0206d394e)
![image](https://github.com/user-attachments/assets/a2198270-7a4a-4e01-891e-84ce4e590c30)
![image](https://github.com/user-attachments/assets/9994af8a-9117-45c2-98cf-0485c3fd4963)
![image](https://github.com/user-attachments/assets/93d241cd-cc08-446a-a29b-1282557823f8)
![image](https://github.com/user-attachments/assets/124bb227-54e8-4087-b79b-34b44d5b1cfe)
![image](https://github.com/user-attachments/assets/a15c9942-038f-4d32-8962-a8e386d8aace)

**Comment by LegendaryElm327** [comment]
[health.zip](https://github.com/user-attachments/files/16822670/health.zip)

**Comment by toxicity188** [comment]
https://discord.com/channels/1012718460297551943/1216391688378126447/1279230060385013790
Try this one please?

**Comment by LegendaryElm327** [comment]
Now works, tysm ^^
