### ISSUE TITLE
Plugin loading order issue with Skript and addons (SkBee, Skript, skript-placeholders, skript-reflect)

### ISSUE THREAD

**Issue by Jeremylo1** [toxicity188/BetterHud#36]
Hi :)

I am currently encountering an issue with the plugin BetterHud when used in combination with Skript and several of its addons, including SkBee, Skript, skript-placeholders, and skript-reflect.

When I start the server, the plugin has trouble loading HUDs if I don't reload BetterHud manually after Skript and its addons are fully loaded. This issue seems to stem from BetterHud being loaded before Skript finishes its registrations, which causes errors in the logs.

Here is the relevant log message:

```
[05:05:05 INFO]: [!] Unable to load this hud: normal_hud in default-hud.yml
[05:05:05 INFO]: [!] Reason: Converters cannot be retrieved until Skript has finished registrations.
```

Would it be possible to adjust the plugin loading order so that BetterHud loads **after** Skript and the following addons:
- SkBee
- Skript
- skript-placeholders
- skript-reflect

This adjustment would prevent the issue of HUDs not being properly loaded on server startup.

Thanks for your help!

P.S. I also want to take a moment to say you're doing an amazing job with Bette
rHud! The fact that you're offering such a fantastic plugin for free is really appreciated, and it’s clear how much effort you put into it. Thank you so much for everything you're doing for the Minecraft community—your work makes a big difference!

[latest.log](https://github.com/user-attachments/files/16902420/latest.log)

**Comment by toxicity188** [comment]
Added in 1.7
