### ISSUE TITLE
ItemsAdder Placeholder support

### ISSUE THREAD

**Issue by JasperRuiz97** [toxicity188/BetterHud#39]
I think it would be great to add the most important placeholder of the plugin, which is Itemsadder.
To explain it in more detail. I can call the star image attached to Itemsadder using the %img_star% format.
But can I show this as a custom placeholder on betterhud? I don't fully understand it.
Since it will only be installed as a placeholder, there is no problem. But when I tried to upload it, it couldn't pull the placeholder.

![image](https://github.com/user-attachments/assets/bf090709-f328-4ce3-b6b9-e9952a079fb0)

example tags images
![image](https://github.com/user-attachments/assets/527818e8-7950-418a-a36d-518ca20a6f7b)
![image](https://github.com/user-attachments/assets/547c3ab1-b3a1-4cb7-885e-c5eb6a527078)

**Comment by toxicity188** [comment]
It can't; ItemsAdder does not support a proper API to implement this in BetterHud.

**Comment by PSYCHEER** [comment]
Always is better to contact someone from our team so you can get close to LoneDev as is and try to resolve these things.
