### ISSUE TITLE
Error java.lang.UnsupportedOperationException: array

### ISSUE THREAD

**Issue by zzzyyylllty** [toxicity188/BetterHud#42]
Server Leaf (Purpur fork) 1.20.4
When updating version 1.0 to 1.4, I find this issue: [https://mclo.gs/pH7vLtv](https://mclo.gs/pH7vLtv)

This is tested error yml section,condiction make this issue (version 1.0,it's working perfectly)

> 
>     7:
>       name: versa
>       pattern: [papi:akacandy_insanity]
>       number-format: '#'
>       outline: true
>       conditions:
>         1:
>           first: (number)papi:akacandy_insanity_C-40
>           second: 0
>           operation: '=='
>           gate: and
>       layer: 1
>       color: white
>       scale: 0.5
>       align: left
>       x: 0
>       y: -2

(`gate:and` section is I added in 1.4)

**Comment by toxicity188** [comment]
key: [] will be considered as array. to prevent this, you have to use "".

7:
  name: versa
  pattern: "[papi:akacandy_insanity]"
  number-format: '#'
  outline: true
  conditions:
    1:
      first: (number)papi:akacandy_insanity_C-40
      second: 0
      operation: '=='
      gate: and
  layer: 1
  color: white
  scale: 0.5
  align: left
  x: 0
  y: -2
