### ISSUE TITLE
How to remove the default minecraft hud?

### ISSUE THREAD

**Issue by MiraslavHub** [toxicity188/BetterHud#44]
I don't understand how to remove the standard hud in minecraft: Food, Health, Experience and possibly inventory
![image](https://github.com/user-attachments/assets/71dd7393-f7a3-44cb-bba2-40952fd12e37)

**Comment by toxicity188** [comment]
Disclaimer
I do NOT accept any request about that.

Closed-source mod/plugin support such as Optifine and ItemsAdder
Hybrid bukkit such as Arclight
Very legacy version such as 1.16.5 or lower
Bedrock platform
A function can cause some significant performance issue.
**Your personal issue**
A function that impossible to implement in server-side such as 144 fps hud.
Inaccurate explanation.
