### ISSUE TITLE
bossbar conflict

### ISSUE THREAD

**Issue by CirrusPreeminent** [toxicity188/BetterHud#48]
`merge-boss-bar: true`

This only works if the boss bar is created after the player has already joined the server. 

However, if a player have just join the server while a boss bar is already active , the HUD still has the squeezed-down issue. 

![2024-10-27_18 13 19](https://github.com/user-attachments/assets/99c57b19-efa2-41bc-bdd6-760dfacb99cf)

- purpur 1.20.4

**Comment by toxicity188** [comment]
Check issue template again.
