### ISSUE TITLE
Crash Oraxen

### ISSUE THREAD

**Issue by P3rsonal1ty** [toxicity188/BetterHud#49]
The betterhud plugin creates a fonts folder inside the Oraxen/pack folder and after that I can't restart Oraxen until I delete this folder
I specified two parameters in config.yml as written in your wiki for Oraxen

![Снимок экрана 2024-11-01 080157](https://github.com/user-attachments/assets/07182a05-da14-4f72-b365-59567da3bc25)

Purpur 1.21.1 windows

**Comment by toxicity188** [comment]
Already patched in #47
