### ISSUE TITLE
Fabric 1.21.3 Placeholders Built in Don't Work Correctly

### ISSUE THREAD

**Issue by SimonMage** [toxicity188/BetterHud#55]
There is an issue on Fabric 1.21.3 where some placeholders built don't work, in particular I saw armor doesn't work and also if you die using a vanilla method the placeholder of health doesn't work correctly and remained stack with an empty bar

![image](https://github.com/user-attachments/assets/ab5e55cf-bb89-4dd3-a2bc-5ae6211a66dd)

- OS (windows)
- Server version (1.21.3)
- Server platform (fabric)

**Comment by SimonMage** [comment]
I made a video in a server with only 3 mods, Fabric API, Polymer and BetterHud
1.21.3

You can see in the video the bug in this issue, please ask more before fast closing issues
https://imgur.com/a/bug-with-betterhud-fabric-1-21-3-RR9Yw0L

**Comment by SimonMage** [comment]
https://i.imgur.com/8cGjPkU.mp4

This is the direct link

**Comment by toxicity188** [comment]
https://modrinth.com/plugin/betterhud2/version/jg0TYCfg
My mistake :(

**Comment by SimonMage** [comment]
Hi, sorry for reopening this issue post, I noticed in 1.21.1 the bug seems remained for the armor bar

**Comment by SimonMage** [comment]
Fabric 1.21.1

**Comment by toxicity188** [comment]
Not happening; ignored.
![2024-11-20_13 22 38](https://github.com/user-attachments/assets/4537b71c-fb78-4af6-adec-43842d055fec)

**Comment by SimonMage** [comment]
I mean the armour bar is empty.
In your screenshot the bar is empty too
