### ISSUE TITLE
[BUG - Fabric 1.21.1] Polymer doesn't load BetterHud ResourcePack on Startup if Polymer is set to AutoHost

### ISSUE THREAD

**Issue by SimonMage** [toxicity188/BetterHud#66]
Hi, simply use Polymer on Fabric 1.21.1 with BetterHud , set AutoHost enabled on Polymer and use /polymer generatepack reload on server to load BetterHud resources on Polymer. Now you can see everything working but after startup of the server, when you re-join the server, polymer loads to you the new resource pack without BetterHud resources, just the other things.

Please fix

**Comment by toxicity188** [comment]
### Please upload your server log when related line exists.
Changed in 1.10.1

**Comment by SimonMage** [comment]
The fix doesn't work, re-open the issue please for Fabric 1.21.1
I have it enabled, this is what I wrote in the issue.
Your mod works only with "/polymer generate-pack" command.

I have Polymer set on AutoHost and the resource pack is not loaded in Polymer on startup.
Here the logs; https://mcpaste.io/eb0f3d618663a9b3


I attached the resource pack generated and as you see in Fabric 1.21.1 BetterHud (default assets) are not merged on startup. 
[resource_pack.zip](https://github.com/user-attachments/files/18113695/resource_pack.zip)

**Comment by SimonMage** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/873ed175-45bb-4f15-b056-38a303edcb60)
I'm using the latest version of BetterHud
