### ISSUE TITLE
colored placeholder can not loaded

### ISSUE THREAD

**Issue by Natsume-999** [toxicity188/BetterHud#67]
if texts in pattern is papi and papi preset to color text , lt will cause the inability to load.
the test_comor_name in the code below is my custom red player name.

`test_layout:
  texts:
    1:
      name: font
      pattern: "[papi:test_color_name]"
.....`

i don't know if this is a bug or not.
but I think this problem is very serious.

**Comment by toxicity188** [comment]
https://modrinth.com/plugin/betterhud2/version/JOln19fg
