### ISSUE TITLE
Issue with mmocore_required_(mana/stamina)_skill:arg, always 0

### ISSUE THREAD

**Issue by AxDevv** [toxicity188/BetterHud#69]
1. The issue seems to be with the placeholder [mmocore_required_stamina_skill:SKILL_NAME] not returning the expected value. It appears to always return 0.

2. Upload some screenshot or text log related your issue. such as:
 [mmocore_required_stamina_skill:METEOR] placeholder
 [mmocore_required_mana_skill:METEOR] placeholder

3. Remember to notice your environment
- Server version : 1.21.3
- Server platform : paper

**Comment by toxicity188** [comment]
No problem happened.

It could be:
```
- Invalid player data
- Invalid stamina value:  all modifier's final value is clamp(base + pre-level * level), min, max)

stamina: #It is 0 because of max value.
  base: 10
  per-level: 5
  min: 0
  max: 0
  ```

**Comment by AxDevv** [comment]
Actually, the plugin looks for stamina and mana in the skill folder of MMOCore and not directly in the classes, which is an issue because the cooldown placeholder works perfectly fine with the class settings.
