### ISSUE TITLE
beta-20 does not work with itemsadder/selfhost is also broken "Failed to download resourcepack"

### ISSUE THREAD

**Issue by czychuuu** [toxicity188/BetterHud#9]
title, purpur 1.20.4

**Comment by toxicity188** [comment]
It is your own problem.
![녹화_2024_05_01_13_14_55_650](https://github.com/toxicity188/BetterHud/assets/114675706/96b7470a-0584-470d-9114-3b01d2ad77f3)

**Comment by czychuuu** [comment]
nah its not my fault it just doesnt work
![image](https://github.com/toxicity188/BetterHud/assets/60987404/fb94db59-c72a-47b2-983b-d162a512478c)
